apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-disk
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  replicas: 1
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: apexacme/prometheus:latest
        imagePullPolicy: Always
        ports:
        - name: webui
          containerPort: 9090
        volumeMounts:
        - mountPath: "/prometheus"
          name: pd
      securityContext:
        fsGroup: 65534
      volumes:
      - name: pd
        persistentVolumeClaim:
          claimName: prometheus-disk
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: NodePort
  ports:
    - port: 9090
      protocol: TCP
      name: webui
  selector:
    app: prometheus
